### ISSUE TITLE
Error Message in Register Page

### ISSUE THREAD

**Issue by saiutkarsh33** [saiutkarsh33/Nusevents#3]
User experience issue - can't see the red error message at the bottom of the sign up form.

**Comment by kwuunnn** [comment]
![image](https://github.com/saiutkarsh33/Nusevents/assets/101648483/6d1301d6-0227-4c15-a7f5-7f82cf099d56)

**Comment by kwuunnn** [comment]
![image](https://github.com/saiutkarsh33/Nusevents/assets/101648483/9958ebfc-a1f7-425b-9753-2113678d9496)

red error message shown at bottom of screen, users may not be able to see the message.

to see the message, they would need to scroll down.

users may be unaware of the reason of the registration error.

**Comment by kwuunnn** [comment]
https://github.com/saiutkarsh33/Nusevents/assets/101648483/59f036f2-f630-48ef-ad52-49ecc5bbdb7b

#4 code that fixed issue
instead of putting the red error message below the submit button, where it may potentially be shown off screen (assuming the submit button is already at the bottom of the screen), i have put the error message above the submit button.

Since the user managed to click the submit button, they can definitely see the button, thus putting the error message above the button instead will ensure that the user will be able to see the error message if any.

**Comment by kwuunnn** [comment]
I will close the issue as it has been resolved.

**Comment by saiutkarsh33** [comment]
Thanks
